let g:moonflyWithGitBranchCharacter = 1
let g:moonflyHonorUserDefinedColors = 1
highlight! link User1 StatusLine
highlight! link User2 DiffAdd
highlight! link User3 DiffChange
highlight! link User4 DiffDelete
highlight! link User5 StatusLine
highlight! link User6 StatusLine
highlight! link User7 StatusLine
